# Generated by Django 3.1 on 2021-04-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='composition',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Composition'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='recipes.recipe'),
        ),
    ]
