# Generated by Django 3.1 on 2021-04-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210419_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='recipes.recipe'),
        ),
    ]
