# Generated by Django 3.1 on 2021-04-19 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210419_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='composition',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='recipes', through='recipes.Composition', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
            preserve_default=False,
        ),
    ]
