# Generated by Django 3.1 on 2021-05-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210507_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'unit')},
        ),
    ]
